CREATE TABLE `sap_time_entry_collection_data`
(
            `ObjectID`                              varchar(70) DEFAULT NULL,
			`UUID`                                  tinyint(1) DEFAULT NULL,
			`InternalID`                            varchar(10) DEFAULT NULL,
			`BusinessPartnerFormattedName`          varchar(480) DEFAULT NULL,
			`ServiceRequestID`                      varchar(35) DEFAULT NULL,
			`AutoTimeRecordingIndicator`            tinyint(1) DEFAULT NULL,
			`BillingRelevanceIndicator`             tinyint(1) DEFAULT NULL,
			`Date`                                  tinyint(1) DEFAULT NULL,
			`Duration`                              varchar(20) DEFAULT NULL,
			`EmployeeUUID`                          tinyint(1) DEFAULT NULL,
			`Description`                           varchar(255) DEFAULT NULL,
			`LanguageCode`                          varchar(2) DEFAULT NULL,
			`EndDateTime`                           tinyint(1) DEFAULT NULL,
			`HeaderReferenceUUID`                   tinyint(1) DEFAULT NULL,
			`ID`                                    varchar(35) NOT NULL,
			`InformationLifeCycleStatusCode`        varchar(2) DEFAULT NULL,
			`ItemReferenceUUID`                     tinyint(1) DEFAULT NULL,
			`BusinessTransactionDocumentTypeCode`   varchar(15) DEFAULT NULL,
			`StartDateTime`                         tinyint(1) DEFAULT NULL,
			`LifeCycleStatusCode`                   varchar(2) DEFAULT NULL,
			`LastChangeDateTime`                    tinyint(1) DEFAULT NULL,
			`TimeReportUUID`                        tinyint(1) DEFAULT NULL,
			`TimeTypeCode`                          varchar(2) DEFAULT NULL,
			`TimeZone`                              varchar(10) DEFAULT NULL,
			`CreationDateTime`                      tinyint(1) DEFAULT NULL,
			`LastChangeIdentityUUID`                tinyint(1) DEFAULT NULL,
			`CreationIdentityUUID`                  tinyint(1) DEFAULT NULL,
			`EmployeeID`                            varchar(60) DEFAULT NULL,
			`EntityLastChangedOn`                   tinyint(1) DEFAULT NULL,
			`ETag`                                  tinyint(1) DEFAULT NULL,
    PRIMARY KEY(`ID`)
) ENGINE = InnoDB
 DEFAULT CHARSET = utf8mb4